import AuthenticatedLayout from "../../../components/AuthenticateCheck";
import "../globals.css";
import Provider from "./../../../components/Provider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={``}>
        <Provider>
          <AuthenticatedLayout>{children}</AuthenticatedLayout>
        </Provider>
      </body>
    </html>
  );
}
