import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });
import "../globals.css";
import LeftSideBar from "../../../components/layout/LeftSideBar";
import MainContainer from "../../../components/layout/MainContainer";
import RightSideBar from "../../../components/layout/RightSideBar";
import TopBar from "../../../components/layout/TopBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.className} bg-slate-100 w-screen overflow-hidden`}
        >
          <TopBar />
          <main className="flex flex-row mt-8">
            <LeftSideBar />
            <MainContainer>{children}</MainContainer>
            <RightSideBar />
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
