import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import "../globals.css";
import LeftSideBar from "../../../components/layout/LeftSideBar";
import RightSideBar from "../../../components/layout/RightSideBar";
import TopBar from "../../../components/layout/TopBar";
import PostDetails from "./component/PostDetails";
import { StoreProvider } from "../store/StoreProvider";
import Drawer from "./component/Drawer";
import BoxChat from "./component/BoxChat";

export const metadata: Metadata = {
  title: "Only Friends",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${inter.className} bg-slate-100 w-screen overflow-hidden relative`}
        >
          <PostDetails />
          <Drawer />
          <TopBar />
          <div className=" flex flex-row gap-3 absolute bottom-[125px] right-32 z-[80]">
            <BoxChat />
          </div>
          <main className="flex flex-row mt-8">
            <LeftSideBar />
            <div>{children}</div>
            <RightSideBar />
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
