import AuthenticatedLayout from "../../../components/AuthenticateCheck";
import Provider from "../../../components/Provider";
import "../globals.css";
import { SocketProvider } from "../socket/socketContext";
import { StoreProvider } from "../store/StoreProvider";

export const metadata = {
  title: "Onlyfriend",
  description: "Generated by Next.js",
};

export default function StreamLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={``}>
        <StoreProvider>
          <Provider>
            <AuthenticatedLayout>
              <SocketProvider>
                     {children}
              </SocketProvider>
            </AuthenticatedLayout>
          </Provider>
        </StoreProvider>
      </body>
    </html>
  );
}
